### ISSUE TITLE
Search result box doesn't always show link click pointer

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/wiki-generator#44]
When I mouse over the faded out links, my pointer doesn't turn into the click finger icon. It will for the links that aren't faded, though.

**Comment by Rafase282** [comment]
@QuincyLarson That is because the fade effect is done by applying an empty `div` element with custom opacity and size, so it would be the same as covering it. Those are not meant to be clickable. However, I did notice that I should expand the height of the article list to give more room for clicking or touch.

This is also the reason for #45
